on:
  push:
    branches:
      - main

name: Generate documentation

jobs:
  api-server:
    name: Generate documentation from OpenAPI schema
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: backend-api/schema/package-lock.json
      - run: ls -a backend-api
      - run: ls -a backend-api/schema
      - run: npm install
        working-directory: ./backend-api/schema
      - run: npm run build:doc -- --output dist/api-server.html
        working-directory: ./backend-api/schema
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: main
          keep_files: true
